### ISSUE TITLE
Validator has some problems on some regexes 

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-continuous-development#102]
Hi,

There are a few issues with some regexes on the `validator.yml` as listed below:

1. Topology ID is based on the OXP URL, and that can contain numbers (see `internet2.net`) which is not covered by the regex `pattern: '^((urn:sdx:topology:)[A-Za-z_.:-]*$)'`
2. Some regex are wrongly using the character `-` in the middle of other characters, which produces wrong results. For instance: `pattern: '^((urn:sdx:node:)[A-Za-z_.-\:]*$)'` this will match all characters between `.` and `:` which does not seems to be what is really expected here.
3. Node names, Interface names, etc can also include numbers, not only A-Za-z characters

Other than that, other SDX project components are using properties that are not defined on the Data model spec, like `Port.short_name`, `Port.label_range`, and `Location.iso3166_2_lvl4`. Although the usage of those properties not defined on the Data model spec is wrong, we have opened tickets there to address this.
 - Meican ISO3166: https://github.com/atlanticwave-sdx/sdx-meican/issues/28
 - Port label range and short_name: https://github.com/atlanticwave-sdx/pce/issues/179 and https://github.com/atlanticwave-sdx/datamodel/issues/102

**Comment by lmarinve** [comment]
Italo, thank you for adjusting the regex not only for ISO3166, but also for other validations. Great job!
