### ISSUE TITLE
mongodb-org-shell unnecessary inside kytos_base Dockerfile and fails to compile on ARM64 targets

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-continuous-development#104]
Hi,

Kytos-base image is failing to build on ARM64 targets (ex: Apple Silicon) because mongodb-org-shell is not available on mongodb official repos.

http://repo.mongodb.org/apt/debian/dists/buster/mongodb-org/5.0/main/binary-arm64/

In fact, I dont see the need for having mongodb-shell inside Kytos-base image. My suggestion would be to remove from there.

**Comment by lmarinve** [comment]
Good morning Italo,

I wanted to update you on a new development that should streamline our work with the OXPO topology conversion and provisioning. We have created a new repository dedicated solely to the essential functions for validating OXPO topology and converting it into the SDX topology API wrapper. This focused approach allows us to enhance the efficiency and maintainability of our codebase.

In this repository, we will be phasing out any superfluous functions that don't directly support these core processes. Here is the link to the new repository: https://github.com/atlanticwave-sdx/oxpo-api-wrapper/issues/9  where all future developments regarding the oxpo-sdx communication will occur. Additionally, we will be providing the /topology and /connection APIs through Nginx and documenting them with Swagger's OpenAPI.

Italo, your expertise is crucial to us. Could you please take a moment to review the repository and share your thoughts? Your feedback is not only important, but it's also invaluable as we continue to progress with this initiative.
